name: Monthly Freight Data Automation

on:
  schedule:
    - cron: "0 6 1 * *"  # 1st of every month at 6 AM UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  automate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run complete automation pipeline
      run: |
        python simple_automation.py
      env:
        # Email notifications will work if these are set as GitHub Secrets
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: freight-data-results
        path: data/
    
    - name: Upload notebooks
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebooks
        path: "*_executed.ipynb"
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Dashboard will be automatically updated when code is pushed to main branch"
        echo "Visit your Streamlit Cloud app to see the updated dashboard"